config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do
    resources :products do
    	collection do
    		get :stock
        get :stock_show
    	end
    end
  end
end

app/models/spree/admin/variant_model_decorator.rb
Spree::Variant.class_eval do
  def friendly_variants
    friendly = []
    self.option_values.each do |v|
      friendly << v.presentation
    end
    friendly.join(' - ')
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  def stock
    @taxons = Spree::Taxon.where(:parent_id => nil)
  end

  def stock_show
    @products = Spree::Product.all(:include => :taxons, :conditions => "spree_taxons.id = #{params[:format]} OR spree_taxons.parent_id = #{params[:format]}")
  end
end

app/views/spree/admin/products/stock.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<h1><%= t(:stock_index_title) %></h1>

<ol>
  <% @taxons.each do |taxon| %>
  <li>
    <%= taxon.name %>
    <ul>
      <% taxon.children.each do |sub| %>
        <li><%= link_to sub.name, stock_show_admin_products_path(sub) %></li>
      <% end %>
    </ul>
  </li>
  <% end %>
</ol>

app/views/spree/admin/products/stock_show.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<h1><%= t(:listing_products) %></h1>
<div id="new_product" data-hook></div>
<table class="index" id="listing_products">
  <tr data-hook="admin_products_index_headers">
    <th><%= t(:taxonomy) %></th>
    <th><%= t(:sku) %></th>
    <th><%= t(:name) %></th>
    <th><%= t(:in_stock) %></th>
  </tr>
<% @products.each do |product| %>
  <tr <%= "style='color: red;'" unless product.has_stock? %> id="<%= dom_id product %>" data-hook="admin_products_index_rows" <%= "class='has_variants'" unless product.variants.empty? %>>
    <td><%= product.taxons.first.name %></td>
    <td><%= product.sku rescue '' %></td>
    <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
    <td><%= product.on_hand %></td>
  </tr>
  <% if !product.variants.empty? %>
  <% product.variants.each do |variant| %>
  <tr class="admin_products_index_rows variant">
    <td></td>
    <td></td>
    <td><%= variant.try(:name) %> - <%= variant.friendly_variants %></td>
    <td><%= variant.on_hand %></td>
  </tr>
  <% end %>
  <% end %>
<% end %>
</table>